# SPDX-License-Identifier: Apache-2.0

CI/CD:
  - changed-file:
      - any-glob-to-any-file:
          - .github/labeler.yml
          - .github/workflows/**/*
          - scripts/ruff.sh
          - .pre-commit-config.yaml
          - .pylintrc
          - .spellcheck-en-custom.txt
          - .spellcheck.yml
          - tox.ini

container:
  - changed-file:
      - any-glob-to-any-file:
          - containers/**/*
          - .dockerignore

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - CODE_OF_CONDUCT.md
          - CONTRIBUTOR_RULES.md
          - governance.md
          - MAINTAINERS.md
          - README.md
          - SECURITY.md
          - TROUBLESHOOTING.md
          - CONTRIBUTING/**/*
          - docs/**/*
          - MAINTAINERS/**/*

testing:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**/*
          - scripts/functional-tests.sh
          - tox.ini
