rules:
  quoted-strings:
    quote-type: any
    required: false
    allow-quoted-quotes: true
    check-keys: true

  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
