id = "nvidia-cuda"
name="nvidia-cuda"
type = "yum-baseurl"
url= "https://developer.download.nvidia.com/compute/cuda/repos/fedora39/x86_64"
gpgcheck=false
gpgkeys=["""-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.22 (GNU/Linux)

mQINBGJYmlEBEACWTlLInNFRO4j0kcXNwaqsFs48ov6rIBXHAip/mRQa4bQQOpLh
Fjx02ubhV/2zoyz6a0uRPYRd7bxLLNUABSFfT/hp14m+jbY0rzO/Y8S42oXUFlbR
2rItp6pQsX5KivAs2FNpXVbEHeojx6XJFDhZkjfOEyoGiMmMgmFZTfiCOU6nGInW
a4JvzPN6hj6GmQMHI2jYim5by2kXYeUg9LlrteV31RzvpyB3chkqeCGgL+bzaRXn
wNZhMZJOAGI+I+wX0kHLFI+T4TU61VxL6RkDrGFJZBXp0Enzq0IcxPA0KoZk4UK5
WG6oth4/eEEcyxFnzIWm1wAJhSOyo1Xxm3475UcP2wEDkW3S0IZt14ZTT1YluUY6
dwiUD8SCInYAfU9CYzHjkBsswiGy47mJTaVnWfjFF+Nk6RJXAN/bcnu6VsZPqM54
mrhWLl34kCorzWKqY1tGIFwo/9wVJ6JXPDs27zq2mX5OpPqcnD/7xdRhar4A/rJ9
dgcwzdhH0ChoFf92Ij+x48tght+NTSHNGysZbdNIFBS1VFg68vgR4vSOSIkiPOU5
gTd2gmVrusrFOPBx+4dq6sxUALb67Z1cS1areq/gCYm5T0eGlX8+KvkLv+temLUj
rscJW0iNibYQJdigPNx66LshdgodTTG+CInc4c4h9USMJZSYwiwhiGqmewARAQAB
tCBjdWRhdG9vbHMgPGN1ZGF0b29sc0BudmlkaWEuY29tPokCOQQTAQIAIwUCYlia
UQIbAwcLCQgHAwIBBhUIAgkKCwQWAgMBAh4BAheAAAoJEJzQpJPULQaFN3AP/RZF
HuO8P1YZhNGl0EpyJkBXlufextNfz2KnjoJNj0+1E8pfR+P1SjROjE6doywVY8DF
XzB1tnp0HVhIxEo/iLMe8AiJDyz/2uHsp+mzc2ZzONxcvB09BTOkCPO7tfbVgsMb
ZFVNIWqiCYEfHjivwymV77Sh9nJYvWfPEPp84V/YVB9lTrBrOUh7G8rjitG3nTbI
ZG6+pkWi3Q9z5GjgtpbnV8AdRNBBPaSTnnZ3gk5cgkJk3CHVf6/6BXvLLicM8k5v
qQhq2MtPExIIAfr8hmg1PLWGLEfAA+3INGTSWXu0HbJNW8bRiVi62wAQFkq5gZLo
wTx6bgQc05dTX+aqBS071KTrICffjlRfrH05JL8HgwWeYC0jG3cGE1cVWSPspCmp
ecnH0CZGrpyCBDUIYho6BXW3IJetSH1WZ8rslYhgIXCPeGpbOQy6//GJzspePZ8M
9gZk9efWfMscwkeGHz10KIdeCacppSeYtOO8CJIBeh79hdW54UO5uadQt/xd+dy6
CSoK7IXjZcVRXbYN11NS4y8B+Q1KHImJj69bQczI4xqibkDJFylUq4NGEYNkH3pL
wuWNVDbw3KpaErRE06bnZHi46u3upICFMpcrSONTX2JYHWnwf8hWKTi/AeMt5TqU
2yZ9xVhsreSa6Wy1VES1sj+6B/ewQTCzRxXqTk3K
=fyUA
-----END PGP PUBLIC KEY BLOCK-----
"""]

