@startditaa
                         +----------------+
                         |ilab init       |-=-taxonomy repo cloned           legend
                         +---+------------+                                  +---------------+
                             |                                               |ilab CLI       |
                             v                                               +---------------+
                         +---+----------------+                              +-----------+
                         |ilab download       |-=-model weights downloaded   |manual cPNK|
                         +---+----------------+                              +-----------+
                             |                                               +-------------+
                             v optional                                      |notebook cYEL|
                         +---+-------------+                                 +-------------+
                         |ilab serve       |-=-start model server
                         +---+-------------+
                             |
                             v
                         +---+------------+
                         |ilab chat       |-=-chat with the model
                         +---+------------+
                             |
                             v
                         +---+------------+
                         |ilab diff       |-=-view the taxonomy diff
                         +---+------------+     expecting nothing
                             |
                             v
                         +---+-----------------------+
                         |contributor creates/updates|
                         |examples in taxonomy   cPNK|<-----------------+
                         +---+-----------------------+                  |
                             |                                          |
                             v                                          |
level 1                  +---+------------+                             |
  only validated     +---|ilab diff       |-=-view the taxonomy diff    |
  the YAML files     |   +---+------------+     and validate YAML files |
                     |       |                                          |
                     |       v                                          |
level 2              |   +---+----------------+                         |
  inspected the      +---|ilab generate       |-------------------------+ -=-synthesize data;
  generated samples  |   +---+----------------++other hardware          |      iterate by modifying examples
                     |       |mac or          |   +--------+----------+ |      if samples do not look good
                     |       vLinux           +-->|notebook train cYEL| |
                     |   +---+-------------+      +--------+----------+ |
                     |   |ilab train       |-=-w/ MLX or   |            |
                     |   +---+-------------+      PyTorch  v            |
                     |       |                  +----------+-------+    |
                     |       v                  |notebook test cYEL+--+ |
level 3              |   +---+------------+     +---------+--------+  | |
  tested generated   +---|ilab test       |---------------|-----------+-+ -=-run unit/smoke tests;
  samples via LoRA   |   +---+------------+               v             |      iterate if some test failed
                     |       |                  +---------+--------+    |
                     |       v optional         |download new model|    |
                     |   +---+---------------+  +-----------------++    |
                     |   |ilab convert       |-=-MLX to GGUF       |    |
                     |   +---+---------------+  +------------------+    |
                     |       |                  |                       |
                     |       v optional         v                       |
                     |   +---+------------------+----+                  |
                     |   |kill ilab serve cPNK       |-=-kill old server|
                     |   +---+-----------------------+                  |
                     |       |                                          |
                     |       v optional                                 |
                     |   +---+-------------+                            |
                     |   |ilab serve       |-=-start server with        |
                     |   +---+-------------+   new model                |
                     |       |                                          |
                     |       v optional                                 |
level 4              |   +---+------------+                             |
  performed the full |   |ilab chat       |-----------------------------+ -=-chat with the model again;
  local smoke test   |   +---+------------+                             |      iterate if not happy with outputs
                     |       |                                          |
                     |       v                                          |
                     |   +---+-------------------------------+          |
                     |   |contributor commits changes and    |          |
                     +-->|creates/updates their PR in the    |          |
                         |taxonomy repo                  cPNK|          |
                         +-----------------+-----------------+          |
                                           |     PR reviewed by taxonomy reviewers;
                                           v       iterate if changes are requested

@endditaa
