@startditaa
+--------+                                    
|lab init|-=---taxonomy repo cloned          legend       
+---+----+                                   +-------+    
    |                                        |lab CLI|    
    v                                        +-------+    
+---+--------+                               +-----------+
|lab download|-=---model weights downloaded  |manual cPNK|
+---+--------+                               +-----------+
    |                                        +----------+
    v                                        |colab cYEL| 
+---+-----+                                  +----------+ 
|lab serve|-=---optional, start model server 
+---+-----+
    |
    v
+---+----+
|lab chat|-=---chat with the model
+---+----+
    |
    v
+---+----+
|lab list|-=---view the taxonomy
+---+----+
    |
    v
+---+---------------------+
|contributor create/update|
|examples in taxonomy cPNK|<------------+
+---+---------------------+             |
    |                                   |
    v                                   |
+---+--------+                          |
|lab generate|--------------------------+ -=---synthesize data;
+---+--------+                          |      iterate by modifying examples
    |                                   |      if samples do not look good
    v                                   | 
+---+----------+                        |
|lab train cYEL|-=---train the model    |
+---+----------+                        |
    |                                   |
    v                                   |
+---+---------+                         |
|lab test cYEL|-------------------------+ -=---run unit/smoke tests;
+---+---------+                         |      iterate if some test failed
    |                                   |
    v                                   |
+---+---------------+                   |
|kill lab serve cPNK|-=---kill server   |
+---+---------------+                   |
    |                                   |
    v                                   |
+---+-----+                             |
|lab serve|-=---start model server      |
+---+-----+                             |
    |                                   |
    v                                   |
+---+----+                              |
|lab chat|------------------------------+ -=---chat with the model again;
+---+----+                                     iterate if not happy with outputs
    |
    v
+---+---------------------------+
|contributor uses Git to commits|
|changes in the taxonomy repo   |
|and create a PR            cPNK|
+---+---------------------------+
@endditaa